spring.profiles.active: develop
server:
  port: 8090
---
spring:
  profiles: develop
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialization-mode: embedded
  h2.console.enabled: true
---
spring:
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialization-mode: embedded
---
resilience4j.thread-pool-bulkhead:
  instances:
    query:
      maxThreadPoolSize: 10
      coreThreadPoolSize: 10
      queueCapacity: 20
      keepAliveDuration: 20
    command:
      maxThreadPoolSize: 10
      coreThreadPoolSize: 10
      queueCapacity: 20
      keepAliveDuration: 20
